name: Build and Deploy Frontend API to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '10.x'

      - name: Build FrontendApi
        run: dotnet build --configuration Release
        working-directory: FrontendApi

      - name: Publish FrontendApi
        run: dotnet publish -c Release -o ./publish
        working-directory: FrontendApi

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontendapi-artifact
          path: FrontendApi/publish

  deploy:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: frontendapi-artifact

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'entry-api-demo'
          slot-name: 'Production'
          package: ./frontendapi-artifact
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FRONTEND }}
